export enum ProductStatus {
  NEW = 'NEW',
  STORED = 'STORED',
  MOVING = 'MOVING',
  REALLOCATE = 'REALLOCATE',
  TEMPORARY = 'TEMPORARY',
  TEMPORARY_OUT = 'TEMPORARY_OUT',
  RECEVIE = "RECEVIE",
  PICKING = "PICKING",
  PACKAGE = "PACKAGE",
  ERROR = "ERROR",
  LOST = "LOST",
  ENABLE = "ENABLE",
  DISABLE = "DISABLE"
}
